import {useMemo,useState} from "react";
import type {ReactNode} from "react";
import {ArrowRight,Check,Clock3,Heart,Home,LogIn,MapPin,Minus,PackageCheck,Plus,Search,Settings,ShoppingBag,Sparkles,Store,Truck,UserRound,X,Zap} from "lucide-react";
import type {Product} from "./data/catalog";
import {categories,initialProducts} from "./data/catalog";
import {makeOrderId,storage,type CartItem,type Order,type OrderStatus,type Session} from "./lib/storage";

type Page="home"|"menu"|"orders"|"account"|"admin";
const demoCustomer:Session={role:"customer",name:"Guest Customer",email:"customer@order-up.demo"};
const demoAdmin:Session={role:"admin",name:"Order-Up Admin",email:"admin@order-up.demo"};
const locations=["Asafo · Kumasi","KNUST Campus · Kumasi","Mobile vans · Kumasi"];
const steps:OrderStatus[]=["Pending","Confirmed","Preparing","Ready","Completed"];
const money=(p:number|null)=>p===null?"Set by admin":"GH₵"+p.toFixed(2);

export default function App(){
 const [page,setPage]=useState<Page>("home"),[products,setProducts]=useState(()=>storage.getProducts(initialProducts)),
 [cart,setCart]=useState<CartItem[]>(()=>storage.getCart()),[orders,setOrders]=useState<Order[]>(()=>storage.getOrders()),
 [session,setSession]=useState<Session|null>(()=>storage.getSession()),[cat,setCat]=useState("All"),[query,setQuery]=useState(""),
 [product,setProduct]=useState<Product|null>(null),[login,setLogin]=useState(false),[checkout,setCheckout]=useState(false),[success,setSuccess]=useState<Order|null>(null),[bag,setBag]=useState(false),[notice,setNotice]=useState("");

 const visible=useMemo(()=>products.filter(p=>(cat==="All"||p.category===cat)&&(!query||p.name.toLowerCase().includes(query.toLowerCase()))),[products,cat,query]);
 const details=cart.map(i=>({i,p:products.find(p=>p.id===i.productId)})).filter(x=>x.p) as {i:CartItem;p:Product}[];
 const count=cart.reduce((a,b)=>a+b.quantity,0),unknown=details.some(x=>x.p.price===null),total=details.reduce((a,x)=>a+(x.p.price??0)*x.i.quantity,0);
 const currentOrders=orders.filter(o=>session?.role==="admin"||o.customerEmail===session?.email);

 const persistCart=(v:CartItem[])=>{setCart(v);storage.saveCart(v)};
 const add=(p:Product)=>{if(!p.available){setNotice(p.name+" is sold out");return;}const found=cart.find(i=>i.productId===p.id);persistCart(found?cart.map(i=>i.productId===p.id?{...i,quantity:i.quantity+1,unitPrice:p.price??i.unitPrice}:i):[...cart,{productId:p.id,quantity:1,unitPrice:p.price??undefined}]);setProduct(null);setNotice(p.name+" added to bag")};
 const change=(id:string,d:number)=>persistCart(cart.map(i=>i.productId===id?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0));
 const signIn=(role:"customer"|"admin")=>{const s=role==="admin"?demoAdmin:demoCustomer;setSession(s);storage.saveSession(s);setLogin(false);setPage(role==="admin"?"admin":"home");setNotice("Welcome to Order-Up")};
 const place=(f:{orderType:"pickup"|"delivery";location:string;address:string;notes:string;paymentReference?:string;paymentMethod?:"MoMo"|"Cash";customerPhone?:string;deliveryFee?:number})=>{
   const s=session??demoCustomer,o:Order={id:makeOrderId(),createdAt:new Date().toISOString(),customerName:s.name,customerEmail:s.email,customerPhone:f.customerPhone,items:cart,orderType:f.orderType,location:f.location,address:f.address,notes:f.notes,paymentReference:f.paymentReference,paymentMethod:f.paymentMethod??"MoMo",deliveryFee:f.deliveryFee??0,status:"Pending"};
   const next=[o,...orders];setOrders(next);storage.saveOrders(next);persistCart([]);setCheckout(false);setBag(false);setSuccess(o);setPage("orders");
 };

 return <div className="app">
  <header className="topbar">
   <button className="brand" onClick={()=>setPage("home")}><span className="brandmark"><Zap size={18}/></span><span><b>Order-Up</b><small>fast food, better flow.</small></span></button>
   <nav>{(["home","menu","orders"] as Page[]).map(x=><button key={x} className={page===x?"nav active":"nav"} onClick={()=>setPage(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}{session?.role==="admin"&&<button className={page==="admin"?"nav active":"nav"} onClick={()=>setPage("admin")}>Admin</button>}</nav>
   <div className="topright"><button className="icon" onClick={()=>setBag(true)}><ShoppingBag size={18}/>{count>0&&<i>{count}</i>}</button><button className="profile" onClick={()=>session?setPage("account"):setLogin(true)}><UserRound size={17}/><span>{session?session.name.split(" ")[0]:"Sign in"}</span></button></div>
  </header>

  <main>
   {page==="home"&&<Home onMenu={()=>setPage("menu")} onAdd={add} products={products}/>}
   {page==="menu"&&<Menu products={visible} cat={cat} setCat={setCat} query={query} setQuery={setQuery} onAdd={add} onSelect={setProduct}/>}
   {page==="orders"&&<Orders session={session} orders={currentOrders} onLogin={()=>setLogin(true)}/>}
   {page==="account"&&<Account session={session} orders={currentOrders} onLogin={()=>setLogin(true)} onLogout={()=>{setSession(null);storage.saveSession(null);setPage("home")}} onAdmin={()=>setPage("admin")}/>}
   {page==="admin"&&session?.role==="admin"&&<Admin products={products} orders={orders} setProducts={(v)=>{setProducts(v);storage.saveProducts(v)}} setOrders={(v)=>{setOrders(v);storage.saveOrders(v)}}/>}
   {page==="admin"&&session?.role!=="admin"&&<Empty title="Admin access only" text="Use the admin demo to open the control room." action={()=>setLogin(true)} actionText="Sign in"/>}
  </main>

  <footer><div><b>Order-Up</b><span>Ordering experience prototype for Wrap n' Roll.</span></div><a href="https://wa.me/233596121704" target="_blank" rel="noreferrer">WhatsApp ↗</a></footer>
  <div className="mobilebar">
   <button className={page==="home"?"active":""} onClick={()=>setPage("home")}><Home size={18}/><span>home</span></button>
   <button className={page==="menu"?"active":""} onClick={()=>setPage("menu")}><Search size={18}/><span>menu</span></button>
   <button className={page==="orders"?"active":""} onClick={()=>session?setPage("orders"):setLogin(true)}><PackageCheck size={18}/><span>orders</span></button>
   <button className={page==="account"?"active":""} onClick={()=>session?setPage("account"):setLogin(true)}><UserRound size={18}/><span>account</span></button>
   <button onClick={()=>setBag(true)}><ShoppingBag size={18}/><span>bag {count?count:""}</span></button>
  </div>

  {product&&<Modal close={()=>setProduct(null)}><div className="productmodal"><img src={product.image}/><div><small>{product.category}</small><h2>{product.name}</h2><p>{product.description}</p><h3>{money(product.price)}</h3><button className="primary wide" onClick={()=>add(product)}>Add to bag <Plus size={17}/></button></div></div></Modal>}
  {bag&&<Modal close={()=>setBag(false)} drawer><h2>Your bag</h2>{details.length===0?<Empty title="Your bag is empty" text="Choose something delicious from the menu."/>:<><div className="cart">{details.map(({i,p})=><div className="cartrow" key={p.id}><img src={p.image}/><div><b>{p.name}</b><span>{money(p.price)}</span><div className="qty"><button onClick={()=>change(p.id,-1)}><Minus size={13}/></button><em>{i.quantity}</em><button onClick={()=>change(p.id,1)}><Plus size={13}/></button></div></div></div>)}</div><div className="total"><span>Total</span><b>{unknown?"Awaiting menu pricing":"GH₵"+total.toFixed(2)}</b></div>{unknown&&<div className="notice">The real menu prices are not published on the reference ordering page, so the admin panel keeps them editable instead of inventing prices.</div>}<button className="primary wide" disabled={unknown||!session} onClick={()=>setCheckout(true)}>{session?"Checkout":"Sign in to checkout"} <ArrowRight size={17}/></button>{!session&&<button className="secondary wide" onClick={()=>setLogin(true)}>Sign in</button>}</>}</Modal>}
  {checkout&&<Checkout total={total} close={()=>setCheckout(false)} onSubmit={place}/>}
  {login&&<Modal close={()=>setLogin(false)}><div className="login"><div className="bubble"><Heart size={20}/></div><small>Account access</small><h2>Welcome to Order-Up.</h2><p>Prototype access is role-based for now. Production auth comes next.</p><button className="primary wide" onClick={()=>signIn("customer")}>Continue as customer</button><button className="secondary wide" onClick={()=>signIn("admin")}>Open admin demo</button></div></Modal>}
  {success&&<Modal close={()=>setSuccess(null)}><div className="success"><div className="parcel">ORDER<br/>UP</div><small>Order received</small><h2>Your order is in the queue.</h2><p><b>{success.id}</b> was created. Track the status from Orders.</p><button className="primary wide" onClick={()=>{setSuccess(null);setPage("orders")}}>Track order <PackageCheck size={17}/></button></div></Modal>}
  {notice&&<div className="toast"><Check size={16}/>{notice}</div>}
 </div>
}

function Home({onMenu,onAdd,products}:{onMenu:()=>void;onAdd:(p:Product)=>void;products:Product[]}){
 const special=products.find(p=>p.id==="triple-taco-box"); const picks=[special,...products.filter(p=>p.id!=="triple-taco-box")].filter(Boolean).slice(0,3) as Product[];
 return <section className="page"><div className="hero"><div><small className="eyebrow"><Sparkles size={13}/> built for hungry humans</small><h1>Order ahead.<br/><span>Eat happy.</span></h1><p>A mobile-first ordering experience inspired by Wrap n' Roll's current menu and order-ahead flow.</p><div className="actions"><button className="primary" onClick={onMenu}>Start an order <ArrowRight size={17}/></button><a className="secondary" href="https://wa.me/233596121704" target="_blank" rel="noreferrer">Order on WhatsApp</a></div><div className="meta"><span><Clock3 size={14}/> Mon–Sun · 8am–11pm</span><span><MapPin size={14}/> Kumasi</span></div></div><div className="heroart"><div className="tag">this week's special</div><div className="food"><div>TACO<br/><small>BOX</small></div></div><b>Triple Taco Box.</b><span>Built for a fast, happy checkout.</span></div></div><div className="sectionhead"><div><small>fan favourites</small><h2>Start with something people love.</h2></div><button className="text" onClick={onMenu}>See full menu <ArrowRight size={16}/></button></div><div className="grid3">{picks.map(p=><Card key={p.id} p={p} onAdd={onAdd}/>)}</div><div className="features"><div>⚡<b>Order to-go</b><span>Pickup or delivery</span></div><div>₵<b>MoMo ready</b><span>Payment reference capture</span></div><div>✓<b>Track progress</b><span>Pending to completed</span></div></div></section>
}

function Menu({products,cat,setCat,query,setQuery,onAdd,onSelect}:{products:Product[];cat:string;setCat:(x:string)=>void;query:string;setQuery:(x:string)=>void;onAdd:(p:Product)=>void;onSelect:(p:Product)=>void}){
 return <section className="page"><div className="sectionhead topmenu"><div><small>the menu</small><h1>Built to order.<br/>Rolled to go.</h1><p>Use the categories or search to find your next meal.</p></div><label className="search"><Search size={17}/><input placeholder="Search the menu" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="chips">{categories.map(c=><button key={c} className={cat===c?"active":""} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="grid4">{products.map(p=><Card key={p.id} p={p} onAdd={onAdd} onSelect={onSelect}/>)}</div>{products.length===0&&<Empty title="No matches yet" text="Try another category or search term."/>}</section>
}

function Card({p,onAdd,onSelect}:{p:Product;onAdd:(p:Product)=>void;onSelect?:(p:Product)=>void}){return <article className="card"><button className="pic" onClick={()=>onSelect?.(p)}><img src={p.image} alt=""/><small>{p.badge}</small>{!p.available&&<em>Sold out</em>}</button><div className="cardbody"><h3>{p.name}</h3><p>{p.description}</p><div className="cardmeta"><span>{p.calories} cal</span><span>{p.prepMinutes} min</span></div><div><b>{money(p.price)}</b><button disabled={!p.available||p.price===null} onClick={()=>onAdd(p)}><Plus size={15}/> {p.available?"Add":"Sold out"}</button></div></div></article>}

function Orders({session,orders,onLogin}:{session:Session|null;orders:Order[];onLogin:()=>void}){return !session?<section className="page center"><Empty title="Track your orders" text="Sign in to see order status and history." action={onLogin} actionText="Sign in"/></section>:<section className="page"><small className="sectionk">your orders</small><h1 className="pageh">Keep an eye on the kitchen.</h1>{orders.length===0?<Empty title="No orders yet" text="Your next meal will appear here."/>:<div className="orderlist">{orders.map(o=><OrderCard key={o.id} o={o}/>)}</div>}</section>}

function OrderCard({o}:{o:Order}){const idx=steps.indexOf(o.status);const fee=o.deliveryFee??0;return <article className="ordercard"><div className="ordhead"><div><small>{o.id}</small><h3>{o.orderType==="pickup"?"Pickup":"Delivery"} · {o.location}</h3></div><span>{o.status}</span></div><div className="tracker">{steps.map((s,i)=><div key={s} className={i<=idx?"done":""}><i>{i<=idx?<Check size={12}/>:i+1}</i><small>{s}</small></div>)}</div><div className="order-summary-line"><span>{o.paymentMethod??"MoMo"}{o.momoNetwork ? " · "+o.momoNetwork : ""}</span><b>{o.paymentReference||"Cash"}</b></div><p>Phone: <b>{o.customerPhone??"Not supplied"}</b> · Delivery fee: <b>GH₵{fee.toFixed(2)}</b></p></article>}
function Account({session,orders,onLogin,onLogout,onAdmin}:{session:Session|null;orders:Order[];onLogin:()=>void;onLogout:()=>void;onAdmin:()=>void}){return <section className="page center"><div className="account">{session?<><div className="avatar"><UserRound/></div><small>{session.role}</small><h1>{session.name}</h1><p>{session.email}</p><div className="stats"><div><b>{orders.length}</b><span>orders</span></div><div><b>24/7</b><span>access</span></div></div>{session.role==="admin"&&<button className="secondary" onClick={onAdmin}><Settings size={16}/> Open admin</button>}<button className="primary" onClick={onLogout}>Sign out</button></>:<><div className="avatar"><LogIn/></div><h1>Sign in to order smarter.</h1><p>Customer ordering and admin controls are included in this challenge MVP.</p><button className="primary" onClick={onLogin}>Continue <ArrowRight size={17}/></button></>}</div></section>}

function Admin({products,orders,setProducts,setOrders}:{products:Product[];orders:Order[];setProducts:(p:Product[])=>void;setOrders:(o:Order[])=>void}){const advance=(id:string)=>setOrders(orders.map(o=>{if(o.id!==id)return o;const i=steps.indexOf(o.status);return {...o,status:steps[Math.min(i+1,steps.length-1)]}}));return <section className="page"><div className="adminhead"><div><small className="sectionk">control room</small><h1 className="pageh">Order-Up Admin</h1><p>Set real prices, switch products on/off and progress orders.</p></div><div className="metrics"><div><b>{products.length}</b><span>products</span></div><div><b>{orders.length}</b><span>orders</span></div></div></div><h2 className="admintitle">Products</h2><div className="ptable">{products.map(p=><div className="prow" key={p.id}><div><b>{p.name}</b><small>{p.category}</small></div><input type="number" min="0" placeholder="Price" value={p.price??""} onChange={e=>setProducts(products.map(x=>x.id===p.id?{...x,price:e.target.value===""?null:Number(e.target.value)}:x))}/><button className={p.available?"toggle on":"toggle"} onClick={()=>setProducts(products.map(x=>x.id===p.id?{...x,available:!x.available}:x))}>{p.available?"Available":"Off"}</button></div>)}</div><h2 className="admintitle">Orders</h2><div className="orderlist">{orders.map(o=><div className="adminorder" key={o.id}><div><b>{o.id}</b><span>{o.customerName} · {o.location}</span></div><div><span>{o.status}</span><button className="secondary small" disabled={o.status==="Completed"} onClick={()=>advance(o.id)}>Advance <ArrowRight size={14}/></button></div></div>)}</div></section>}

function Checkout({total,close,onSubmit}:{total:number;close:()=>void;onSubmit:(f:{orderType:"pickup"|"delivery";location:string;address:string;notes:string;paymentReference?:string;paymentMethod?:"MoMo"|"Cash";customerPhone?:string;deliveryFee?:number})=>void}){const [type,setType]=useState<"pickup"|"delivery">("pickup"),[loc,setLoc]=useState(locations[0]),[address,setAddress]=useState(""),[notes,setNotes]=useState(""),[ref,setRef]=useState(""),[method,setMethod]=useState<"MoMo"|"Cash">("MoMo"),[network,setNetwork]=useState("MTN MoMo"),[phone,setPhone]=useState("");const deliveryFee=type==="delivery"?15:0;const grandTotal=total+deliveryFee;const disabled=!phone.trim()||(type==="delivery"&&!address.trim())||(method==="MoMo"&&!ref.trim());return <Modal close={close}><div className="checkout"><small>checkout</small><h2>One more step.</h2><p>Choose pickup or delivery, then select how you want to pay.</p><div className="summary"><div><span>Subtotal</span><b>GH₵{total.toFixed(2)}</b></div><div><span>Total</span><b>GH₵{grandTotal.toFixed(2)}</b></div></div><div className="segment"><button className={type==="pickup"?"active":""} onClick={()=>setType("pickup")}><Store size={16}/> Pickup</button><button className={type==="delivery"?"active":""} onClick={()=>setType("delivery")}><Truck size={16}/> Delivery + GH₵15</button></div><label>Location<select value={loc} onChange={e=>setLoc(e.target.value)}>{locations.map(x=><option key={x}>{x}</option>)}</select></label>{type==="delivery"&&<label>Delivery address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Hostel, house or landmark"/></label>}<label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="024 xxx xxxx"/></label><div className="segment"><button className={method==="MoMo"?"active":""} onClick={()=>setMethod("MoMo")}><Wallet size={16}/> MoMo</button><button className={method==="Cash"?"active":""} onClick={()=>setMethod("Cash")}>Cash</button></div>{method==="MoMo"&&<><div className="notice"><b>MoMo: 0596 121 704</b><br/>Send GH₵{grandTotal.toFixed(2)} then enter your transaction reference.</div><label>Network<select value={network} onChange={e=>setNetwork(e.target.value)}><option>MTN MoMo</option><option>Telecel Cash</option><option>AT Money</option></select></label><label>Transaction reference<input value={ref} onChange={e=>setRef(e.target.value)} placeholder="e.g. 835219"/></label></>}<label>Note<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Extra sauce, no onions, gate directions..." rows={3}/></label><button className="primary wide" disabled={disabled} onClick={()=>onSubmit({orderType:type,location:loc,address,notes,paymentMethod:method,paymentReference:method==="MoMo"?ref:undefined,customerPhone:phone,deliveryFee})}>Place order <PackageCheck size={17}/></button></div></Modal>}


function Empty({title,text,action,actionText}:{title:string;text:string;action?:()=>void;actionText?:string}){return <div className="empty"><ShoppingBag size={30}/><h2>{title}</h2><p>{text}</p>{action&&<button className="primary" onClick={action}>{actionText}</button>}</div>}
function Modal({children,close,drawer=false}:{children:ReactNode;close:()=>void;drawer?:boolean}){return <div className="backdrop" onMouseDown={close}><div className={drawer?"modal drawer":"modal"} onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X size={18}/></button>{children}</div></div>}
